#! /bin/bash
dwstat pools
echo " *.jobid error:"
grep -i err run/*.jobid
echo "          *.sh: $(ls run/*.sh  | wc)"
echo "       *.jobid: $(ls run/*.jobid | wc)"
echo "         *.out: $(ls run/*.out | wc)"
echo "showq  $LOGNAME: $(showq -u $LOGNAME | grep $LOGNAME | wc)"
echo "showq  running: $(showq -u $LOGNAME | grep "$LOGNAME.*Running" | wc)"
echo "showq stageout: $(showq -v -u $LOGNAME | grep "stageout.*Running" | wc)"
showq -v | grep active
echo "*.out non-run90 && non-success:"
egrep -L "run90|RESULT: SUCCESS" run/*.out | xargs ls -ld run/.  
echo "*.out FAILURE|signal|killed:"
egrep -l "FAILURE|signal|killed" run/*.out | xargs ls -ld run/.  
