#! /bin/bash
datefmt="+%Y-%m-%d %H:%M:%S"
echo "$(date "$datefmt") =============================================================================="
dir=${1-run}
echo "Searching: $(realpath $dir)"

dwstat pools
echo "          *.sh: $(ls $dir/*.sh  | wc -l)"
echo "       *.jobid: $(ls $dir/*.jobid | wc -l)"
echo "         *.out: $(ls $dir/*.out | wc -l)"
echo "showq  $LOGNAME: $(showq -u $LOGNAME | grep $LOGNAME | wc -l)"
echo "showq  running: $(showq -u $LOGNAME | grep "$LOGNAME.*Running" | wc -l)"
echo "showq stageout: $(showq -v -u $LOGNAME | grep "stageout.*Running" | wc -l )"
showq -v | grep active
echo " *.jobid error:"
grep -i err $dir/*.jobid
echo "*.out non-run90 && non-success:"
egrep -L "run90|RESULT: SUCCESS" $dir/*.out | xargs ls -ld $dir/.  
echo "*.out FAILURE|failed|signal|killed:"
egrep -l "FAILURE|failed|signal|killed" $dir/*.out | xargs ls -ld $dir/.  
