#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Read and write N-N test case with read data value checking.
# Test various ID values on read.

#  hvsd datawarp_stage_mode immediate is set to force all datasets to be retained

if [[ ${HIO_TEST_ROOTS/DataWarp//} == $HIO_TEST_ROOTS ]]; then
  echo "Test $0 only valid valid with DataWarp.  Exiting."
  exit 77
fi

batch_sub $(( 3 * $ranks * $blksz * $nblk ))

cmdw="
  name run09w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS

  hda NTNDS 98 WRITE,CREAT UNIQUE hdo
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  s 1

  hda NTNDS 97 WRITE,CREAT UNIQUE hdo
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  s 1

  hda NTNDS 96 WRITE,CREAT UNIQUE hdo
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  hf mgf mf
"

cmdr="
  name run09r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS

  hxdi 97
  hvp c. .
  hda NTNDS 97 READ UNIQUE hdo
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf

  hxdi 98
  hda NTNDS ID_HIGHEST READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf

  qof 2 hxdi 96
  hda NTNDS ID_NEWEST READ UNIQUE hdo
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf

  hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdr
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
exit $max_rc
