#! /bin/bash
. ./run_setup

# Read and write N-N test case with read data value checking.
# Dataset staged to scratch and deleted from DataWarp prior
# to read. Multiple dataset staged.

if [[ ${HIO_TEST_ROOTS/DataWarp//} == $HIO_TEST_ROOTS ]]; then
  echo "Test $0 only valid valid with DataWarp.  Exiting."
  exit 77
fi

batch_sub $(( 3 * $ranks * $blksz * $nblk ))

cmdw="
  name run07w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS

  hda NTNDS 97 WRITE,CREAT UNIQUE hdo
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  hda NTNDS 98 WRITE,CREAT UNIQUE hdo
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  hda NTNDS 99 WRITE,CREAT UNIQUE hdo
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  hf mgf mf
"

cmdr="
  name run07r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS
  hda NTNDS 99 READ UNIQUE hdo
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw

# Wait for directory stage out to complete
cmd aprun -n 1 .libs/xexec.x v 3 dwds $HIO_datawarp_root/MYCTX.hio/NTNDS/97
cmd aprun -n 1 .libs/xexec.x v 3 dwds $HIO_datawarp_root/MYCTX.hio/NTNDS/98
cmd aprun -n 1 .libs/xexec.x v 3 dwds $HIO_datawarp_root/MYCTX.hio/NTNDS/99

# delete the datawarp directory
clean_roots "DataWarp"

# Now read the dataset from 2nd data root (PFS)
myrun .libs/xexec.x $cmdr

check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
