#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Read and write N-1 test case with read data value checking.

batch_sub $(( $ranks * $blksz * $nblkpseg * $nseg ))

cmdw="
  name run03w v $verbose_lev d $debug_lev mi 0
  /@@ Write N-1 test case @/
  dbuf RAND22P 20Mi
  hi MY_CTX $HIO_TEST_ROOTS
  hdu NT1_DS 98 ALL
  hda NT1_DS 98 WRITE,CREAT SHARED hdo
  heo MY_EL WRITE,CREAT,TRUNC
  hvp c. .
  lc $nseg
    hsegr 0 $segsz 0
    lc $nblkpseg
      hew 0 $blksz
    le
  le
  hec hdc hdf hf mgf mf
"

cmdr="
  name run03r v $verbose_lev d $debug_lev mi 32
  /@@ Read N-1 test case with data checking @/
  dbuf RAND22P 20Mi
  hi MY_CTX $HIO_TEST_ROOTS
  hda NT1_DS 98 READ SHARED hdo
  heo MY_EL READ
  hvp c. .
  lc $nseg
    hsegr 0 $segsz 17
    lc $nblkpseg
      her 0 $blksz
    le
  le
  hec hdc hdf hf mgf mf
"

#set -x
clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
# Don't read if write failed
if [[ max_rc -eq 0 ]]; then
  myrun .libs/xexec.x $cmdr
  # If first read fails, try again to see if problem persists
  if [[ max_rc -ne 0 ]]; then
    myrun .libs/xexec.x $cmdr
  fi
fi
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
exit $max_rc
