#! /bin/bash
. ./run_setup

# Read and write N-N test case with read data value checking.

batch_sub $(( $ranks * $blksz * $nblk ))

cmdw="
  name run02w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS
  hda NTNDS 97 WRITE,CREAT UNIQUE hdo
  heo MYEL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf hf mgf mf
"

cmdr="
  name run02r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS
  hda NTNDS 97 READ UNIQUE hdo
  heo MYEL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdr
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
