#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Create and reuse N-N dataset - i.e., ensure TRUNC works
batch_sub $(( $ranks * $blksz * $nblk ))

cmdw="
  name run05w v $verbose_lev d $debug_lev mi 0
  /@@ Create and reuse N-N dataset - i.e., ensure TRUNC works @/
  hi MY_CTX $HIO_TEST_ROOTS
  hda NTN_DS 97 WRITE,CREAT,TRUNC UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf hf mgf mf
"

cmdr="
  name run05r v $verbose_lev d $debug_lev mi 0
  /@@ Create and reuse N-N dataset - i.e., ensure TRUNC works @/
  hi MY_CTX $HIO_TEST_ROOTS
  hda NTN_DS 97 READ UNIQUE hdo
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdr
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
