#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Simple non-MPI API test

batch_sub $(( $ranks * $cons_mi ))

cfg_file="test01.tmp.hio.cfg"

clean_roots $HIO_TEST_ROOTS

set -x
echo "#HIO.data_roots=$HIO_TEST_ROOTS" > $cfg_file
ranks=1     # Since test01 is non-MPI
myrun .libs/test01.x $cfg_file
set +x

check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
