#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Read and write N-N test case with randomized counts and lengths and read data value checking.

blkszM=$(($blksz*12/10))
nblkM=$(($nblk*12/10))

batch_sub $(( $ranks * $blkszM * $nblkM ))

cmdw="
  name run12w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write random N-N test case with read data value checking @/
  dbuf RAND22P 20Mi
  hi MY_CTX $HIO_TEST_ROOTS
  hda NTN_DS 97 WRITE,CREAT UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC
  hvp c. .
  srr 100
  lcr $nblk $nblkM
    hewr 0 $blksz $blkszM 32
  le
  hec hdc hdf hf mgf mf
"

cmdr="
  name run12r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write random N-N test case with read data value checking @/
  dbuf RAND22P 20Mi
  hi MY_CTX $HIO_TEST_ROOTS
  hda NTN_DS 97 READ UNIQUE hdo
  heo MY_EL READ
  hvp c. .
  srr 100
  lcr $nblk $nblkM
    herr 0 $blksz $blkszM 32
  le
  hec hdc hdf hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
# Don't read if write failed
if [[ max_rc -eq 0 ]]; then
  myrun .libs/xexec.x $cmdr
  # If first read fails, try again to see if problem persists
  if [[ max_rc -ne 0 ]]; then
    myrun .libs/xexec.x $cmdr
  fi
fi
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
exit $max_rc
