#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Read and write N-N test case with read data value checking.
# Based on run02, modified to test DW phase 2 caching
# Hard coded paths, etc, not for general purpose testing

case $size in
  t ) blk=1k;   nblk=5;;
  s ) blk=20ki; nblk=8;;
  m ) blk=1Mi;  nblk=200;;
  l ) blk=2Mi;  nblk=512;;
  x ) blk=2Mi;  nblk=1024;;
  * ) synexit "Error: invalid size $size";;
esac

msg "blk: $blk  nblk: $nblk  segsz: $segsz  nseg: $nseg"

cache="/dwphase2/cornell"
pfs="/ufs/home/dwphase2/cornell"

cmdwc="
  /@@ Write cache @/
  name run10wc v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$cache
  hda NTN_DS 97 WRITE,CREAT UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew -$blk $blk
  le
  hec hdc hdf hf mgf mf
"

cmdrc="
  /@@ Read cache @/
  name run102rc v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$cache
  hda NTN_DS 97 READ UNIQUE hdo
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her -$blk $blk
  le
  hec hdc hdf hf mgf mf
"

cmdwp="
  /@@ Write backing FS @/
  name run10wp v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$pfs
  hda NTN_DS 97 WRITE,CREAT UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew -$blk $blk
  le
  hec hdc hdf hf mgf mf
"

cmdrp="
  /@@ Read backing FS @/
  name run102rp v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$pfs
  hda NTN_DS 97 READ UNIQUE hdo
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her -$blk $blk
  le
  hec hdc hdf hf mgf mf
"

#clean_roots $HIO_TEST_ROOTS
nfs_sleep=61

#set -x

# Clean up - erase cache, flush cache, list cache, pfs
aprun -n 1 -b bash -xc "strace -f -o strace.out.1 rm -fR $cache/*"
aprun -n 1 -b bash -xc "mkdir -p $cache"
aprun -n 1 -b bash -xc "mkdir -p $pfs"
aprun -n 1 -b bash -xc "find $cache -type f | xargs -n 1 -I {} /users/henseler/testioctl {} wsync"
#aprun -n 1 -b bash -xc "find $cache -type f | xargs -n1 -t ./xexec.x dwws"
aprun -n 1 -b bash -xc "find $cache -ls"
sleep $nfs_sleep
aprun -n 1 -b bash -xc "find $pfs -ls"

# Write PFS, read PFS, read cache 2X
myrun .libs/xexec.x $cmdwp
myrun .libs/xexec.x $cmdrp
sleep $nfs_sleep
myrun .libs/xexec.x $cmdrc
myrun .libs/xexec.x $cmdrc
check_rc

# Clean up - erase cache, flush cache, list cache, pfs
aprun -n 1 -b bash -xc "strace -f -o strace.out.1 rm -fR $cache/*"
aprun -n 1 -b bash -xc "find $cache -type f | xargs -n 1 -I {} /users/henseler/testioctl {} wsync"
#aprun -n 1 -b bash -xc "find $cache -type f | xargs -n1 -t ./xexec.x dwws"
aprun -n 1 -b bash -xc "find $cache -ls"
sleep $nfs_sleep
aprun -n 1 -b bash -xc "find $pfs -ls"


# Write cache, flush cache, read PFS, read cache 2X
myrun .libs/xexec.x $cmdwc
aprun -n 1 -b bash -xc "find $cache -type f | xargs -n 1 -I {} /users/henseler/testioctl {} wsync"
#aprun -n 1 -b bash -xc "find $cache -type f | xargs -n1 -t ./xexec.x dwws"
sleep $nfs_sleep
myrun .libs/xexec.x $cmdrp
sleep $nfs_sleep
myrun .libs/xexec.x $cmdrc
myrun .libs/xexec.x $cmdrc
check_rc
exit $max_rc
