#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Dataset ID management test

batch_sub $(( $ranks * $blksz * $nblk ))

c_init="
  name run21 v $verbose_lev d $debug_lev mi 0
  /@@ run21 - dataset ID management test @/
  dbuf RAND22P 20Mi
  hi MYCTX $HIO_TEST_ROOTS
  opt -XPERF 
"

c_w1="
  hda NTNDS ID_NEXT WRITE,CREAT UNIQUE hdo
  heo MYEL WRITE,CREAT,TRUNC
  lc $nblk
    hew 0 $blksz
  le
  hec hdc
  hvp . \"resident.|.last\"
"

c_fini="
  hf mgf mf
"


# /@ n n @/ indicates expected extant DS IDs
cmd="$c_init
     $c_w1 hdf $c_w1
     /@ 1 2 @/
     hvai pd resident_id_count EQ 2 hdf
     $c_w1
     /@ 2 3 @/
     hvai pd resident_id_count EQ 2 
     hvsc datawarp_keep_last 4 hdf
     $c_w1
     /@ 2 3 4 @/
     hvai pd resident_id_count EQ 3 hdf 
     $c_w1
     /@ 2 3 4 5 @/
     hvai pd resident_id_count EQ 4 hdf
     $c_w1
     /@ 3 4 5 6 @/
     hvai pd resident_id_count EQ 4 
     hvsc datawarp_keep_last 3 hdf
     $c_w1
     /@ 5 6 7 @/
     hvai pd resident_id_count EQ 3 hdf
     hdu NTNDS 6 CURRENT
     /@ 5 7 @/
     hvai pd resident_id_count EQ 2
     hdu NTNDS 7 CURRENT
     /@ 5 @/
     hvai pd resident_id_count EQ 1
     hdu NTNDS 5 CURRENT
     /@ none @/
     hvai pd resident_id_count EQ 0
     $c_w1
     /@ 8 @/
     hvai pd resident_id_count EQ 1 hdf
     $c_w1
     /@ 8 9 @/
     hvai pd resident_id_count EQ 2 hdf
     $c_w1
     /@ 8 9 10 @/
     hvai pd resident_id_count EQ 3 hdf
     $c_w1
     /@ 9 10 11 @/ 
     hvai pd resident_id_count EQ 3 hdf
     $c_fini
"

echo $cmd

clean_roots $HIO_TEST_ROOTS

myrun $HIO_TEST_XEXEC $cmd
  
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
exit $max_rc
