#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Read and write N-N test case with read data value checking.
# Check for correct DS ID for ID_HIGHEST and ID_NEWEST

batch_sub $(( 3 * $ranks * $blksz * $nblk ))

cmdw="
  name run20w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write N-N multi DS test case @/
  dbuf RAND22P 20Mi
  hi MY_CTX $HIO_TEST_ROOTS

  hda NTN_DS 97 WRITE,CREAT UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC
  hvp c. .
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  s 1
  hda NTN_DS 98 WRITE,CREAT UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC
  hvp c. .
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  s 1
  hda NTN_DS 99 WRITE,CREAT UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC
  hvp c. .
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf

  hf mgf mf
"

cmdr="
  name run20r v $verbose_lev d $debug_lev mi $HIO_TEST_MI_SHIFT
  /@@ Read and write N-N multi DS test case @/
  dbuf RAND22P 20Mi
  hi MY_CTX $HIO_TEST_ROOTS

  hxdi 99
  hda NTN_DS 99 READ UNIQUE hdo
  heo MY_EL READ
  hvp c. .
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf

  hxdi 99
  hda NTN_DS ID_NEWEST READ UNIQUE hdo
  heo MY_EL READ
  hvp c. .
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf

  hxdi 99
  hda NTN_DS ID_HIGHEST READ UNIQUE hdo
  heo MY_EL READ
  hvp c. .
  lc $nblk
    her 0 $blksz
  le
  hec hdc hdf

  hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun $HIO_TEST_XEXEC $cmdw
# Don't read if write failed
if [[ max_rc -eq 0 ]]; then
  myrun $HIO_TEST_XEXEC $cmdr
  # If first read fails, try again to see if problem persists
  if [[ max_rc -ne 0 ]]; then
    myrun $HIO_TEST_XEXEC $cmdr
  fi
fi
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
exit $max_rc
