#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Dataset ID management test

batch_sub $(( $ranks * $blksz * $nblk ))

c_init="
  name run21 v $verbose_lev d $debug_lev mi 0
  /@@ run21 - dataset ID management test @/
  dbuf RAND22P 20Mi
  hi MYCTX $HIO_TEST_ROOTS
  opt -XPERF 
"

c_w1() {
  exp=$1
  if [[ -n $2 ]]; then keep="hvsd datawarp_keep_last $2"
  else keep=""; fi
  echo -n " 
    hda NTNDS ID_NEXT WRITE,CREAT UNIQUE
    $keep hdo 
    v 0 heo MYEL WRITE,CREAT,TRUNC
    lc $nblk
      hew 0 $blksz
    le
    hec v $verbose_lev hdc 
    hvai pd resident_id_count EQ $exp 
    hvp . \"resident.|.last\"
    hdf
  "
}

c_fini="
  hf mgf mf
"

# /@ n n @/ indicates expected extant DS IDs after next write
cmd="$c_init
     /@@ 1 @/
     `c_w1 1`

     /@@ 2 @/
     `c_w1 1`

     /@@ 2 3 @/
     `c_w1 2 4`

     /@@ 2 3 4 @/
     `c_w1 3`

     /@@ 2 3 4 5 @/
     `c_w1 4`

     /@@ 3 4 5 6 @/
     `c_w1 4`

     /@@ 5 6 7 @/
     `c_w1 3 3`

     /@@ 5 7 @/
     hdu NTNDS 6 CURRENT
     hvai pd resident_id_count EQ 2

     /@@ 5 @/
     hdu NTNDS 6 CURRENT
     hvai pd resident_id_count EQ 1

     /@@ none @/
     hdu NTNDS 5 CURRENT
     hvai pd resident_id_count EQ 0

     /@@ 8 @/
     `c_w1 1`

     /@@ 8 9 @/
     `c_w1 2`

     /@@ 8 9 10 @/
     `c_w1 3`

     /@@ 9 10 11 @/
     `c_w1 3`

     /@@ 10 11 12 @/
     `c_w1 3`
"

cmd="$cmd $c_fini"

echo $cmd

clean_roots $HIO_TEST_ROOTS

myrun $HIO_TEST_XEXEC $cmd

myrun find $DW_JOB_STRIPED
  
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
exit $max_rc
