#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Write N-N test case with subsequent hdu.

batch_sub $(( $ranks * $blksz * $nblk ))

cmdw="
  name run81 v $verbose_lev d $debug_lev mi 0
  /@@ Write N-N test case @/
  dbuf RAND22P 20Mi
  hi MYCTX $HIO_TEST_ROOTS
  hda NTNDS 97 WRITE,CREAT UNIQUE hdo
  heo MYEL WRITE,CREAT,TRUNC
  hvp c. .
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf
  hf mgf mf
"

cmdwu="
  name run81 v $verbose_lev d $debug_lev mi 0
  /@@ Write N-N test case @/
  dbuf RAND22P 20Mi
  hi MYCTX $HIO_TEST_ROOTS
  hda NTNDS 97 WRITE,CREAT UNIQUE hdo
  heo MYEL WRITE,CREAT,TRUNC
  hvp c. .
  lc $nblk
    hew 0 $blksz
  le
  hec hdc hdf
  ifr 0
    v 2 hdu NTNDS 97 ALL v $verbose_lev
  eif
  hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
cmd "aprun -n 1 bash -c \"find $DW_JOB_STRIPED | wc -l \""
myrun $HIO_TEST_XEXEC $cmdwu
cmd "aprun -n 1 bash -c \"find $DW_JOB_STRIPED | wc -l \""

clean_roots $HIO_TEST_ROOTS
cmd "aprun -n 1 bash -c \"find $DW_JOB_STRIPED | wc -l \""
myrun $HIO_TEST_XEXEC $cmdw
# Comment out find command since it may influence rm -fR speed
#cmd "aprun -n 1 bash -c \"find $DW_JOB_STRIPED | wc -l \""
clean_roots $HIO_TEST_ROOTS
cmd "aprun -n 1 bash -c \"find $DW_JOB_STRIPED | wc -l \""
  
check_rc
exit $max_rc

