#! /bin/bash
# -*- Mode: sh; sh-basic-offset:2 ; indent-tabs-mode:nil -*-
#
# Copyright (c) 2014-2016 Los Alamos National Security, LLC.  All rights
#                         reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

. ./run_setup

# Submit two secondary DataWarp job from the launched job.
# A.K.A. "Wabbit"
# Uses -p (PPN) to regulate depth

# CAUTION CAUTIONi CAUTION CAUTION CAUTION CAUTION CAUTION CAUTION CAUTION
# -p should specify a SMALL number since (2**p)-2 jobs will eventually be
# submitted ! (That's the exponential 2 to the power p !!!!!)
# CAUTION CAUTIONi CAUTION CAUTION CAUTION CAUTION CAUTION CAUTION CAUTION

ppn=$(( $ppn - 1 ))

if [[ $ppn -gt 0 ]]; then
  echo "ppn: $ppn; resubmitting"
  batch=2
  batch_sub 1
  batch_sub 1
else
  echo "ppn: $ppn; doing nothing"
fi
