#! /bin/bash -x
export DYLD_LIBRARY_PATH=$PWD/../.libs

cfg_file="test01.cfg"
test_dir="$PWD/test_root1"
echo "#HIO.context_data_roots=POSIX:$PWD/$test_dir" > $cfg_file
mkdir -p $test_dir
rm -fR $test_dir/*

./test01.x $cfg_file
