#! /bin/bash -x

#

test_dir="$PWD/test_root1"
cmd="v 2 d 1 mi hi ctx_name POSIX:$test_dir hdo dsn_name 22 65 0 d 2 heo el_name 0 20Mi hew 0 12Mi hec hdc hf mf"

mkdir -p $test_dir
 
rm -fR $test_dir/*
./xexec2.x $cmd

rm -fR $test_dir/*
mpirun -mca orte_tag_output 1 -n 2 ./xexec2.x $cmd
