#! /bin/bash -x
export DYLD_LIBRARY_PATH=$PWD/../.libs

test_dir="$PWD/.test_root1"
cfg_file="$test_dir/test01.cfg"

mkdir -p $test_dir
rm -fR $test_dir/*
echo "#HIO.data_roots=POSIX:$test_dir" > $cfg_file

./test01.x $cfg_file
