.\" -*- nroff -*-
.\" Copyright 2016 Los Alamos National Security, LLC. All rights
.\" reserved.
.\" $COPYRIGHT$
.TH hio_ds_info 1 "October 2016" libhio "User Manuals"
.SH NAME
hio_ds_info \- dump hio dataset metadata
.SH SYNOPSIS
\fBhio_ds_info [--all] [--elements] [--rank <rank>] [--config]
[--perform] <data root> <context name> [dataset name [dataset id]]\fP
.SH DESCRIPTION
\fBhio_ds_info\fP dumps the metadata from dataset(s) in a
human-readable format.
.SH OPTIONS
.IP --all | -a
Dump all the metadata from dataset(s).
.IP --elements | -e
Dump element metadata from dataset(s).
.IP --rank | -r
Dump metadata associated with a specific rank (unique offset mode
only).
.IP --config | -c
Dump dataset configuration variables.
.IP --perform | -p
Dump dataset performance variables.
.SH AUTHOR
Nathan Hjelm <hjelmn at cs dot unm dot edu>
\fB
