#! /bin/bash 
. ./run_setup

# Simple non-MPI API test

batch_sub $(( $ranks * $cons_mi ))

cfg_file="test01.tmp.hio.cfg"

clean_roots $HIO_TEST_ROOTS

set -x
echo "#HIO.data_roots=$HIO_TEST_ROOTS" > $cfg_file
myrun .libs/test01.x $cfg_file
set +x

check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
