#! /bin/bash 
. ./run_setup

# Read and write N-N test case with read data value checking.
# Test various ID values on read.

#  hvsd datawarp_stage_mode immediate is set to force all datasets to be retained

batch_sub $(( 3 * $ranks * $blksz * $nblk ))

cmdw="
  name run09w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS

  hdo NTNDS 98 WRITE,CREAT UNIQUE
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz 
  le 
  hec hdc

  s 1

  hdo NTNDS 97 WRITE,CREAT UNIQUE
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz 
  le 
  hec hdc

  s 1

  hdo NTNDS 96 WRITE,CREAT UNIQUE
  hvsd datawarp_stage_mode immediate
  hvp c. .
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nblk
    hew 0 $blksz 
  le 
  hec hdc

  hf mgf mf
"

cmdr="
  name run09r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write N-N test case with read data value checking @/
  hi MYCTX $HIO_TEST_ROOTS 

  hxdi 97
  hvp c. .     
  hdo NTNDS 97 READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .     
  hck on
  lc $nblk
    her 0 $blksz 
  le 
  hec hdc

  hxdi 98
  hdo NTNDS ID_HIGHEST READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .     
  hck on
  lc $nblk
    her 0 $blksz 
  le 
  hec hdc

  qof 2 hxdi 96
  hdo NTNDS ID_NEWEST READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .     
  hck on
  lc $nblk
    her 0 $blksz 
  le 
  hec hdc

  hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdr
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
