#! /bin/bash
. ./run_setup

# Invalid parameter test cases 
# Much more needed 

fails="
  name run04w v $verbose_lev d $debug_lev mi 0
  /@@ HDO without prior init @/
    hxrc ERR_BAD_PARAM 
    hdo NT1_DS 98 WRITE,CREAT SHARED

  /@@ HI, HDO CREAT in non-writable context directory @/
    hi MY_CTX POSIX:/does_not_exist 
    hxrc ERR_PERM 
    hdo NTN_DS 97 WRITE,CREAT UNIQUE
    hf

  /@@ HI, HDO READ in non-existant context directory @/
    hi MY_CTX POSIX:/does_not_exist 
    hxrc ERR_NOT_FOUND
    hdo NTN_DS 97 READ UNIQUE
    hf

  /@@ HI, HDO invalid data root prefix @/
    hi MY_CTX WIERD:/does_not_exist 
    hxrc ERR_NOT_FOUND 
    hdo NTN_DS 97 WRITE,CREAT UNIQUE
    hf

  /@@ HEO without HDO @/
    hxrc ERR_BAD_PARAM 
    heo MY_EL WRITE,CREAT,TRUNC 20Mi

  /@@ HI, HDO READ non-existant DS ID  @/
    hi MY_CTX $HIO_TEST_ROOTS
    hxrc ERR_NOT_FOUND 
    hdo NTN_DS 97 READ UNIQUE
    hf

  mgf mf
"

#set -x
clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec2.x $fails
