#! /bin/bash
. ./run_setup

cmdw="v 2 d 1 mi hi ctx_name POSIX:$root hdo dsn_name 22 65 0 d 2 heo el_name 0 20Mi lc 100 hew 0 12Mi le hec hdc hf mf"
cmdr="v 2 d 1 mi hi ctx_name POSIX:$root hdo dsn_name 22 0  0 d 2 heo el_name 0 20Mi lc 100 her 0 12Mi le hec hdc hf mf"

set -x
mpirun -mca orte_tag_output 1  ./xexec2.x $cmdw
mpirun -mca orte_tag_output 1  ./xexec2.x $cmdr

