#! /bin/bash
. ./run_setup

# Read and write N-1 test case with read data value checking.  

case $size in
  t ) blk=1k;   nblk=5;  segsz=5k;    nseg=2;;
  s ) blk=20ki; nblk=8;  segsz=160ki; nseg=10;;
  m ) blk=1Mi;  nblk=16; segsz=16Mi;  nseg=16;;
  l ) blk=2Mi;  nblk=16; segsz=32Mi;  nseg=32;;
  x ) blk=2Mi;  nblk=32; segsz=64Mi;  nseg=32;; 
  * ) synexit "Error: invalid size $size";;
esac

msg "blk: $blk  nblk: $nblk  segsz: $segsz  nseg: $nseg" 

cmdw="
  /@@ Write N-1 test case @/  
  name run03w v $verbose_lev d $debug_lev mi 0
  hi MY_CTX $HIO_TEST_ROOTS
  hdu NT1_DS 98 ALL 
  hdo NT1_DS 98 WRITE,CREAT SHARED
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  lc $nseg
    hsegr 0 $segsz 0
    lc $nblk
      hew -$blk $blk 
    le 
  le 
  hec hdc hf mgf mf
"

cmdr="
  /@@ Read N-1 test case with data checking @/  
  name run03r v $verbose_lev d $debug_lev mi 0
  hi MY_CTX $HIO_TEST_ROOTS 
  hdo NT1_DS 98 READ SHARED
  heo MY_EL READ 20Mi
  hck on
  lc $nseg
    hsegr 0 $segsz 17
    lc $nblk
      her -$blk $blk 
    le 
  le 
  hec hdc hf mgf mf
"

#set -x
clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec2.x $cmdw
myrun .libs/xexec2.x $cmdr
check_rc
