#! /bin/bash 
. ./run_setup

# Read and write N-N test case with read data value checking.
# Based on run02, modified to test DW phase 2 caching
# Hard coded paths, etc, not for general purpose testing  

case $size in
  t ) blk=1k;   nblk=5;;
  s ) blk=20ki; nblk=8;;   
  m ) blk=1Mi;  nblk=200;;
  l ) blk=2Mi;  nblk=512;;
  x ) blk=2Mi;  nblk=1024;;
  * ) synexit "Error: invalid size $size";;
esac

msg "blk: $blk  nblk: $nblk  segsz: $segsz  nseg: $nseg" 

cache="/dwphase2/cornell"
pfs="/ufs/home/dwphase2/cornell"

cmdwc="
  /@@ Read and write N-N test case with read data value checking @/
  name run10wc v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$cache 
  hdo NTN_DS 97 WRITE,CREAT UNIQUE
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew -$blk $blk 
  le 
  hec hdc hf mgf mf
"

cmdrc="
  /@@ Read and write N-N test case with read data value checking @/
  name run102rc v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$cache 
  hdo NTN_DS 97 READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her -$blk $blk 
  le 
  hec hdc hf mgf mf
"

cmdwp="
  /@@ Read and write N-N test case with read data value checking @/
  name run10wp v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$pfs 
  hdo NTN_DS 97 WRITE,CREAT UNIQUE
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew -$blk $blk 
  le 
  hec hdc hf mgf mf
"

cmdrp="
  /@@ Read and write N-N test case with read data value checking @/
  name run102rp v $verbose_lev d $debug_lev mi 0
  hi MY_CTX posix:$pfs 
  hdo NTN_DS 97 READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her -$blk $blk 
  le 
  hec hdc hf mgf mf
"

#clean_roots $HIO_TEST_ROOTS

# Clean up - erase cache, flush cache, list cache, pfs
aprun -n 1 -b bash -c "rm -fR $cache/*"
aprun -n 1 -b bash -c "mkdir -p $cache"
aprun -n 1 -b bash -c "mkdir -p $pfs"
aprun -n 1 ./users/heneseler/testioctl $cache wsync
aprun -n 1 -b bash -c "find $cache -ls"
aprun -n 1 -b bash -c "find $pfs -ls"

# Write PFS, read PFS, read cache 2X
myrun .libs/xexec.x $cmdwp
myrun .libs/xexec.x $cmdrp
myrun .libs/xexec.x $cmdrc
myrun .libs/xexec.x $cmdrc
check_rc

# Clean up - erase cache, flush cache, list cache, pfs
aprun -n 1 -b bash -c "rm -fR $cache/*"
aprun -n 1 ./users/heneseler/testioctl $cache wsync
aprun -n 1 -b bash -c "find $cache -ls"
aprun -n 1 -b bash -c "find $pfs -ls"


# Write cache, flush cache, read PFS, read cache 2X
myrun .libs/xexec.x $cmdwc
aprun -n 1 ./users/heneseler/testioctl $cache wsync
myrun .libs/xexec.x $cmdrp
myrun .libs/xexec.x $cmdrc
myrun .libs/xexec.x $cmdrc
check_rc
