#! /bin/bash 
. ./run_setup

# Read and write N-N test case with randomized counts and lengths and read data value checking.  

case $size in
  t ) blk=1024;                nblk=5;;
  s ) blk=20480;               nblk=8;;   
  m ) blk=$((1 * $cons_mi));  nblk=200;;
  l ) blk=$((2 * $cons_mi));  nblk=512;;
  x ) blk=$((4 * $cons_mi));  nblk=1024;;
  * ) synexit "Error: invalid size $size";;
esac

blkM=$(($blk*12/10))
nblkM=$(($nblk*12/10))

batch_sub $(( $blkM * $nblkM * $ranks ))

msg "blk: $blk - $blkM  nblk: $nblk - $nblkM  dw_cap: $dw_cap" 

cmdw="
  name run12w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write random N-N test case with read data value checking @/
  hi MY_CTX $HIO_TEST_ROOTS 
  hdo NTN_DS 97 WRITE,CREAT UNIQUE
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  srr 100
  lcr $nblk $nblkM 
    hewr 0 $blk $blkM 32 
  le 
  hec hdc hf mgf mf
"

cmdr="
  name run12r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write random N-N test case with read data value checking @/
  hi MY_CTX $HIO_TEST_ROOTS 
  hdo NTN_DS 97 READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  srr 100
  lcr $nblk $nblkM
    herr 0 $blk $blkM 32 
  le 
  hec hdc hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdr
check_rc
if [[ $max_rc == 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
