#! /bin/bash 
. ./run_setup

# Read and write N-N test case with randomized counts and lengths and read data value checking.  

blkszM=$(($blksz*12/10))
nblkM=$(($nblk*12/10))

batch_sub $(( $ranks * $blkszM * $nblkM ))

cmdw="
  name run12w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write random N-N test case with read data value checking @/
  hi MY_CTX $HIO_TEST_ROOTS 
  hda NTN_DS 97 WRITE,CREAT UNIQUE hdo
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  srr 100
  lcr $nblk $nblkM 
    hewr 0 $blksz $blkszM 32 
  le 
  hec hdc hdf hf mgf mf
"

cmdr="
  name run12r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write random N-N test case with read data value checking @/
  hi MY_CTX $HIO_TEST_ROOTS 
  hda NTN_DS 97 READ UNIQUE hdo
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  srr 100
  lcr $nblk $nblkM
    herr 0 $blksz $blkszM 32 
  le 
  hec hdc hdf hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdr
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
