#! /bin/bash 
. ./run_setup

# Read and write N-N test case with read data value checking.  
# Check for correct DS ID for ID_HIGHEST and ID_NEWEST

batch_sub $(( 3 * $ranks * $blksz * $nblk ))

cmdw="
  name run20w v $verbose_lev d $debug_lev mi 0
  /@@ Read and write N-N multi DS test case @/
  hi MY_CTX $HIO_TEST_ROOTS 

  hdo NTN_DS 97 WRITE,CREAT UNIQUE
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew 0 $blksz 
  le 
  hec hdc

  s 1
  hdo NTN_DS 98 WRITE,CREAT UNIQUE
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew 0 $blksz 
  le 
  hec hdc

  s 1
  hdo NTN_DS 99 WRITE,CREAT UNIQUE
  heo MY_EL WRITE,CREAT,TRUNC 20Mi
  hvp c. .
  lc $nblk
    hew 0 $blksz 
  le 
  hec hdc

  hf mgf mf
"

cmdr="
  name run20r v $verbose_lev d $debug_lev mi 32
  /@@ Read and write N-N multi DS test case @/
  hi MY_CTX $HIO_TEST_ROOTS 

  hxdi 99
  hdo NTN_DS 99 READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz 
  le 
  hec hdc

  hxdi 99
  hdo NTN_DS ID_NEWEST READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz 
  le 
  hec hdc

  hxdi 99
  hdo NTN_DS ID_HIGHEST READ UNIQUE
  heo MY_EL READ 20Mi
  hvp c. .
  hck on
  lc $nblk
    her 0 $blksz 
  le 
  hec hdc

  hf mgf mf
"

clean_roots $HIO_TEST_ROOTS
myrun .libs/xexec.x $cmdw
myrun .libs/xexec.x $cmdr
check_rc
if [[ $max_rc -eq 0 && $after -gt 0 ]]; then clean_roots $HIO_TEST_ROOTS; fi
