CC      = gcc -g -O0 -Wall -fPIC
MPICC      = mpicc -g -O0 -Wall -fPIC
MPI_ROOT        = /users/hng
HDF5_SRC        = /users/hng/hdf5-1.8.16/src
HIO             = /users/hng
INSTALL_PREFIX  = /users/hng
CFLAGS          = -I$(INSTALL_PREFIX)/include -I$(HIO)
LDFLAGS         = -L$(INSTALL_PREFIX)/lib -L$(HIO)
